### PR TITLE
Allow requesting specific attributes

### PR DESCRIPTION
**Pull request by xjunior**
- Remove nil attributes from response
- Allow to selectively serialize attributes with to_scim
- Request specific attributes through ActiveRecordBackedResourcesController

Closes https://github.com/RIPAGlobal/scimitar/issues/89

### CODE REVIEW

**Comment by xjunior** [comment]
Please, let me know if there's anything that I'm missing or could be better.

**Comment by xjunior** [comment]
I'm really sorry to bother you with PR's, but we're looking to incorporate this feature in our SCIM server, and we might not be able to wait much longer. We're looking for feedback on this and perhaps move this work forward. Thank you

**Comment by xjunior** [comment]
Can I get a review on this PR?

**Comment by web-kat** [comment]
Hi @pond we would really love to use this feature in our SCIM implementation. How can we move forward with this PR?

**Comment by pond** [comment]
I've been too busy to get to this, but looking at it today.

Please do remember that anyone at any time can fork a gem with their own additions, to incorporate something that they have as a PR but is waiting on a maintainer. Your Gemfile just references the fork.

```
gem 'foo', git: 'https://github.com/myaccount/forked-gem-name.git', branch: 'something'
```

...so you don't need to wait on me to use a gem modification; you can in the short term use a fork or PR branch directly.

**Comment by xjunior** [comment]
The other option is to fork for a brief moment as you suggested, we were just trying to avoid the overhead of doing it as much as we could hold.

**Comment by pond** [comment]
@xjunior 

> we'll come to a deadline next week, so I was wondering if you think this PR could make it until then

Well I can't be held to external third party unspecified deadlines, obviously. If the PR makes it in time, then great. As it stands, #109 passes CI though I have a feeling I should have a lot more tests in there...

Please if you have time could you try using this in your `Gemfile` to load Scimitar from PR 109's branch directly and see if that's doing what you need? Our own tests pass this way but they've never exercised as many features or edge cases as some of the gem's contributors evidently have!

```ruby
gem 'scimitar', git: 'https://github.com/RIPAGlobal/scimitar', branch: 'feature/fix-non-returnables'
```

**Comment by pond** [comment]
@xjunior OK, so this now has a lot of conflicts (as expected) after #109 went in.

I can't fix these as your new +attributes+ parameter is undocumented. I don't know whether that's meant to be local data model attributes, SCIM attributes, if the latter whether that's described as dotted paths, arrays, or what, whether it's Symbols, or Strings, or...

...so, first thing, since you've added a new parameter to an already parameter-heavy back end method, please do take care to follow the existing commentary and indentation style to document your new parameter. Then we're in a position to assess how flexible that is, and how it should be applied to the heavily updated from-SCIM backend code.

**Comment by xjunior** [comment]
@pond I'll work on fixing these conflicts and following your suggestions, thank you!

**Comment by pond** [comment]
@xjunior Thanks. I don't mind this PR being a smaller implementation where e.g. it only handles non-schema prefix attributes etc., it's fine to take baby steps, but yeah defo please do the docs & have a think about parameter names with an eye to potential future changes.

I'll try to expedite a review, timezones permitting, once you give me a shout that it's ready for another look.

**Comment by pond** [comment]
Merging this into a feature branch for further experimentation and hopefully inclusion in a release.

**Pull request merged**
